x-uffizzi:
  ingress:
    service: app
    port: 8000

services:
  app:
    build: .
    deploy:
      resources:
        limits:
          memory: 4000M
    restart: always
    ports:
      - "8000:8000"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
volumes:
  data:
